{
  "target": "http://localhost:12345/webdav",
  "base_path": "testfiles",
  "platform": "Unknown",
  "client_id": "bcdd26a53a33",
  "timestamp": "2025-06-22T14:11:01.360541",
  "results": [
    {
      "test_path": "bcdd26a53a33_test_file.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_test_file.txt",
      "timestamp": "2025-06-22T14:11:01.314578",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_test_file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac05f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_../test_file.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_../test_file.txt",
      "timestamp": "2025-06-22T14:11:01.318719",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_../test_file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390aaecf0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_../../test_file.txt",
      "full_url": "http://localhost:12345/testfiles/test_file.txt",
      "timestamp": "2025-06-22T14:11:01.322447",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/test_file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac0fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_%252e%252e/test_file.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_%252e%252e/test_file.txt",
      "timestamp": "2025-06-22T14:11:01.326092",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_%252e%252e/test_file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac1550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_./test_file.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_./test_file.txt",
      "timestamp": "2025-06-22T14:11:01.329925",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_./test_file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac1be0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_test_file/..txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_test_file/..txt",
      "timestamp": "2025-06-22T14:11:01.333557",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_test_file/..txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac2270>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_test_file/./.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_test_file/.txt",
      "timestamp": "2025-06-22T14:11:01.337267",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_test_file/.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac2ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_test_file\\.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_test_file\\.txt",
      "timestamp": "2025-06-22T14:11:01.341019",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_test_file%5C.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac2c00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_..\\test_file.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_..\\test_file.txt",
      "timestamp": "2025-06-22T14:11:01.344560",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_..%5Ctest_file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac1c10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_test\u2024file.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_test\u2024file.txt",
      "timestamp": "2025-06-22T14:11:01.348231",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_test%E2%80%A4file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac2f60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_test%5ffile.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_test%5ffile.txt",
      "timestamp": "2025-06-22T14:11:01.351752",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_test_file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac3350>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    },
    {
      "test_path": "bcdd26a53a33_test%20file.txt",
      "full_url": "http://localhost:12345/testfiles/bcdd26a53a33_test%20file.txt",
      "timestamp": "2025-06-22T14:11:01.355375",
      "payload_type": "uuid",
      "success": false,
      "put_status": null,
      "get_status": null,
      "delete_status": null,
      "platform": "Unknown",
      "client_id": "bcdd26a53a33",
      "error": "HTTPConnectionPool(host='localhost', port=12345): Max retries exceeded with url: /testfiles/bcdd26a53a33_test%20file.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0390ac3d10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
    }
  ],
  "request_history": []
}